name: Build ESP
on: [push]
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Compile
      run: cl /std:c++20 /EHsc /O2 fivem_esp.cpp /link d3d11.lib dxgi.lib user32.lib gdi32.lib /out:fivem_esp.exe
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: ESP_EXE
        path: fivem_esp.exe
